version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    env_file:
      - ./backend/database/postgresDocker.env
    ports:
      - "5432:5432"